apiVersion: v1
kind: Service
metadata:
  name: tensorboard
  labels:
    name: tensorboard
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 6006
  selector:
    app: tensorboard
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tensorboard
  name: tensorboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorboard
  template:
    metadata:
      labels:
        app: tensorboard
    spec:
      volumes:
        - name: azure-files
          persistentVolumeClaim:
            claimName: azure-files
      containers:
        - name: tensorflow
          image: tensorflow/tensorflow:1.9.0
          imagePullPolicy: Always
          volumeMounts:
            - name: azure-files
              mountPath: /tf-logs
              subPath: tfjob1b-edsheeran
          ports:
            - containerPort: 6006
              protocol: TCP              